# Generated by Django 6.1.1 on 2026-10-03 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '���������',
                'verbose_name_plural': '���������',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='catalog.category')),
            ],
            options={
                'verbose_name': '�������������',
                'verbose_name_plural': '�������������',
                'ordering': ['category', 'name'],
                'constraints': [models.UniqueConstraint(fields=('category', 'name'), name='unique_problem_per_category')],
            },
        ),
    ]
