# Generated by Django 6.1.1 on 2026-10-03 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='problem',
            options={'ordering': ['category', 'name'], 'verbose_name': 'Неисправность', 'verbose_name_plural': 'Неисправности'},
        ),
    ]
