# Generated by Django 6.1.1 on 2026-10-03 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_alter_category_options_alter_problem_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('problem_text', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=150)),
                ('house', models.CharField(max_length=30)),
                ('apartment', models.CharField(blank=True, max_length=30)),
                ('address_comment', models.TextField(blank=True)),
                ('visit_date', models.DateField()),
                ('time_slot', models.CharField(choices=[('09_12', '09:00–12:00'), ('12_15', '12:00–15:00'), ('15_18', '15:00–18:00'), ('18_21', '18:00–21:00')], max_length=20)),
                ('customer_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=30)),
                ('customer_comment', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'Новая'), ('accepted', 'Принята'), ('assigned', 'Назначен мастер'), ('on_the_way', 'Мастер выехал'), ('completed', 'Выполнена'), ('canceled', 'Отменена')], default='new', max_length=20)),
                ('internal_comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='catalog.category')),
                ('problem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='catalog.problem')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
    ]
