# Generated by Django 6.1.1 on 2026-10-03 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_category_options_alter_problem_options'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address_comment',
            field=models.TextField(blank=True, verbose_name='Комментарий к адресу'),
        ),
        migrations.AlterField(
            model_name='order',
            name='apartment',
            field=models.CharField(blank=True, max_length=30, verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='order',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='catalog.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_comment',
            field=models.TextField(blank=True, verbose_name='Комментарий клиента'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(max_length=100, verbose_name='Имя клиента'),
        ),
        migrations.AlterField(
            model_name='order',
            name='house',
            field=models.CharField(max_length=30, verbose_name='Дом'),
        ),
        migrations.AlterField(
            model_name='order',
            name='internal_comment',
            field=models.TextField(blank=True, verbose_name='Внутренний комментарий'),
        ),
        migrations.AlterField(
            model_name='order',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=100, verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True, verbose_name='Номер заявки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=30, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='order',
            name='problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='catalog.problem', verbose_name='Неисправность'),
        ),
        migrations.AlterField(
            model_name='order',
            name='problem_text',
            field=models.CharField(blank=True, max_length=255, verbose_name='Описание проблемы'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('accepted', 'Принята'), ('assigned', 'Назначен мастер'), ('on_the_way', 'Мастер выехал'), ('completed', 'Выполнена'), ('canceled', 'Отменена')], default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='street',
            field=models.CharField(max_length=150, verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_slot',
            field=models.CharField(choices=[('', 'Выберите временной интервал'), ('09_12', '09:00–12:00'), ('12_15', '12:00–15:00'), ('15_18', '15:00–18:00'), ('18_21', '18:00–21:00')], max_length=20, verbose_name='Временной интервал'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее изменение'),
        ),
        migrations.AlterField(
            model_name='order',
            name='visit_date',
            field=models.DateField(verbose_name='Дата визита'),
        ),
    ]
