# Generated by Django 6.1.1 on 2026-10-04 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_address_comment_alter_order_apartment_and_more'),
        ('workers', '0002_alter_worker_working_days'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='assigned_worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='workers.worker', verbose_name='Назначенный мастер'),
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, choices=[('new', 'Новая'), ('accepted', 'Принята'), ('assigned', 'Назначен мастер'), ('on_the_way', 'Мастер выехал'), ('completed', 'Выполнена'), ('canceled', 'Отменена')], max_length=20, verbose_name='Старый статус')),
                ('new_status', models.CharField(choices=[('new', 'Новая'), ('accepted', 'Принята'), ('assigned', 'Назначен мастер'), ('on_the_way', 'Мастер выехал'), ('completed', 'Выполнена'), ('canceled', 'Отменена')], max_length=20, verbose_name='Новый статус')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Время изменения')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Изменение статуса',
                'verbose_name_plural': 'История статусов',
                'ordering': ['-changed_at'],
            },
        ),
    ]
