# Generated by Django 6.1.1 on 2026-10-04 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='working_days',
            field=models.JSONField(blank=True, default=list, verbose_name='Рабочие дни'),
        ),
    ]
